apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kwirth.fullname" . }}-cr
  labels:
  {{- include "kwirth.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
